spring.application.name=person-api

spring.datasource.url=jdbc:mysql://localhost:3306/person_db?useSSL=False
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

